### ISSUE TITLE
1x InFlight_Load/InFlight_Load.lua:129: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)

### ISSUE THREAD

**Issue by Hollicsh** [rursache/InFlight-TWW#2]
1x InFlight_Load/InFlight_Load.lua:129: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@InFlight_Load/InFlight_Load.lua"]:129: in function `SetupInFlight'
[string "@InFlight_Load/InFlight_Load.lua"]:21: in function `?'
[string "@InFlight_Load/InFlight_Load.lua"]:3: in function <InFlight_Load/InFlight_Load.lua:3>

Locals:
self = InFlight {
 L = <table> {
 }
}
panel = Frame {
 name = "InFlight"
}
(*temporary) = nil
(*temporary) = Frame {
 name = "InFlight"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
InFlight = InFlight {
 L = <table> {
 }
}

**Comment by rursache** [comment]
Add the steps to reproduce this issue or I'll close it..

**Comment by Hollicsh** [comment]
I just go into the game and get this error.

**Comment by rursache** [comment]
Its safe to ignore it for now, it will get fixed soon. meantime run: 
```
/console scriptErrors 0
```
in chat to hide lua errors

**Comment by Daveo7** [comment]
To fix this...

In InFlight_Load/InFlight_Load.lua remove...

InterfaceOptions_AddCategory(panel)

...and replace it with these two lines...

local category = Settings.RegisterCanvasLayoutCategory(self, "InFlight")
Settings.RegisterAddOnCategory(category)

**Comment by rursache** [comment]
fixed in https://github.com/rursache/InFlight-WW/releases/tag/v11.0.0
