### ISSUE TITLE
Flight timer bar not showing with Quartz3 - Flight

### ISSUE THREAD

**Issue by nrpieper** [rursache/InFlight-TWW#22]
Using the Quartz 3 castbar, there is default option to show the flight time on the Quartz cast bar. With this enabled, the InFlight-TWW bar never displays and Quartz3 also doesn't display the flight timer countdown on it's castbar.  InFlight used to work with Quartz3 to show flight times on the Quartz cast bar.  Can you please take a look at the issue and either work with Quartz3 or just show the InFlight-TWW castbar regardless of the Quartz3 - Flight option.

![image](https://github.com/user-attachments/assets/02a4401f-ed23-42d3-b678-ff295932a589)

Thanks,
Nathan - author of: Misspelled

**Comment by rursache** [comment]
could be the same issue as https://github.com/rursache/InFlight-TWW/issues/19

currently this addon is in maintenance mode, no new features are added and we are just making sure it works in the current WoW version. I am not using quartz and have no plans into fixing this

if you or anyone else could chime it, pull requests are welcome!
