### ISSUE TITLE
Curseforge dead link

### ISSUE THREAD

**Issue by Vampire2008** [rursache/InFlight-TWW#4]
It returns 404

**Comment by Vampire2008** [comment]
Why? You could you [BigWids WoW packager](https://github.com/marketplace/actions/wow-packager) to automate pubish.

**Comment by rursache** [comment]
curseforge rejected the package, its not something i can do!

**Comment by rursache** [comment]
they changed their mind and approved it: https://www.curseforge.com/wow/addons/inflight-ww
