### ISSUE TITLE
LUA Error on load

### ISSUE THREAD

**Issue by WhyteDem0n** [rursache/InFlight-TWW#7]
Getting a LUA error after today's patch:

Message: Interface/AddOns/InFlight_Load/InFlight_Load.lua:42: attempt to call global 'GetAddOnEnableState' (a nil value)
Time: Tue Aug 13 18:50:17 2024
Count: 1
Stack: Interface/AddOns/InFlight_Load/InFlight_Load.lua:42: attempt to call global 'GetAddOnEnableState' (a nil value)

Locals:

**Comment by WhyteDem0n** [comment]
Getting another LUA error when starting a flight and the flgiht bar never loads:

Message: Interface/AddOns/InFlight_Load/InFlight_Load.lua:9: attempt to call global 'LoadAddOn' (a nil value)
Time: Tue Aug 13 19:49:55 2024
Count: 2
Stack: Interface/AddOns/InFlight_Load/InFlight_Load.lua:9: attempt to call global 'LoadAddOn' (a nil value)
[string "@Interface/AddOns/InFlight_Load/InFlight_Load.lua"]:9: in function <Interface/AddOns/InFlight_Load/InFlight_Load.lua:7>
[string "@Interface/AddOns/InFlight_Load/InFlight_Load.lua"]:34: in function `?'
[string "@Interface/AddOns/InFlight_Load/InFlight_Load.lua"]:3: in function <Interface/AddOns/InFlight_Load/InFlight_Load.lua:3>

Locals: (*temporary) = nil
(*temporary) = "InFlight"
(*temporary) = "attempt to call global 'LoadAddOn' (a nil value)"
InFlight = InFlight {
}

**Comment by WhyteDem0n** [comment]
didn't mean to close T_T

**Comment by superwario15** [comment]
I've submitted a pull request with fixes for this issue.

**Comment by rursache** [comment]
duplicate of https://github.com/rursache/InFlight-WW/issues/9
