### ISSUE TITLE
Login error in 11.0.2

### ISSUE THREAD

**Issue by jgleigh** [rursache/InFlight-TWW#9]
1x InFlight_Load/InFlight_Load.lua:42: attempt to call global 'GetAddOnEnableState' (a nil value)
[string "@InFlight_Load/InFlight_Load.lua"]:42: in main chunk

Locals:
InFlight = InFlight {
}
self = InFlight {
}
(*temporary) = nil
(*temporary) = "Kharthus"
(*temporary) = "InFlight"
(*temporary) = "attempt to call global 'GetAddOnEnableState' (a nil value)"

**Comment by superwario15** [comment]
I've submitted a pull request with fixes for this issue.

**Comment by Rav99** [comment]
@superwario15 nice work but pls check line 48 ->2x if is not good :)
